# Generated by Django 6.0.2 on 2026-02-07 04:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amenity_type', models.CharField(choices=[('popular', 'Most Popular'), ('apartment', 'Apartment Features'), ('service', 'Services & Safety'), ('facility', 'Facilities'), ('inroom', 'In-room Amenities')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('icon_name', models.CharField(blank=True, help_text="Font Awesome icon name (e.g., 'fa-wifi')", max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Amenity',
                'verbose_name_plural': 'Amenities',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='gallery/%Y/%m/')),
                ('category', models.CharField(choices=[('living', 'Living Room'), ('bedroom', 'Bedroom'), ('kitchen', 'Kitchen'), ('bathroom', 'Bathroom'), ('dining', 'Dining Area'), ('exterior', 'Exterior'), ('amenities', 'Amenities'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('alt_text', models.CharField(help_text='Alt text for accessibility', max_length=200)),
                ('order', models.IntegerField(default=0, help_text='Lower numbers appear first')),
                ('is_featured', models.BooleanField(default=False, help_text='Show on home page')),
                ('is_active', models.BooleanField(default=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
                'ordering': ['order', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Summer Weekend' or 'Winter Weekday'", max_length=100)),
                ('season', models.CharField(choices=[('peak', 'Peak Season'), ('regular', 'Regular Season'), ('off', 'Off Season')], default='regular', max_length=20)),
                ('base_price_per_night', models.DecimalField(decimal_places=2, help_text='Base price per night in USD', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('start_date', models.DateField(blank=True, help_text='Leave blank for year-round', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Leave blank for year-round', null=True)),
                ('weekly_discount_percent', models.DecimalField(decimal_places=2, default=0, help_text='Discount for 7+ nights (percentage)', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('monthly_discount_percent', models.DecimalField(decimal_places=2, default=0, help_text='Discount for 30+ nights (percentage)', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('cleaning_fee', models.DecimalField(decimal_places=2, default=0, help_text='One-time cleaning fee', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('service_fee_percent', models.DecimalField(decimal_places=2, default=0, help_text='Service fee percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pricing Rule',
                'verbose_name_plural': 'Pricing Rules',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Urban Oasis', max_length=100)),
                ('tagline', models.CharField(default='Your home away from home', max_length=200)),
                ('address', models.CharField(default='5110 Daybreak Dr, Killeen, TX 76542', max_length=200)),
                ('phone', models.CharField(default='+1 (407) 900-6046', max_length=20)),
                ('email', models.EmailField(default='hello@urbanoasis.com', max_length=254)),
                ('check_in_time', models.TimeField(default='15:00')),
                ('check_out_time', models.TimeField(default='11:00')),
                ('facebook_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('max_guests', models.IntegerField(default=6)),
                ('num_bedrooms', models.IntegerField(default=3)),
                ('num_bathrooms', models.IntegerField(default=2)),
                ('square_feet', models.IntegerField(default=1172)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('num_guests', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('special_requests', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pricing_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rentals.pricingrule')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=100)),
                ('rating', models.IntegerField(help_text='Rating from 1 to 5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MinValueValidator(5)])),
                ('comment', models.TextField()),
                ('is_approved', models.BooleanField(default=False, help_text='Show on website')),
                ('is_featured', models.BooleanField(default=False, help_text='Feature on home page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rentals.booking')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
