# Generated by Django 6.0.2 on 2026-02-07 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingrule',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description shown on pricing cards'),
        ),
        migrations.AddField(
            model_name='pricingrule',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional image for the pricing card', null=True, upload_to='pricing/'),
        ),
        migrations.AddField(
            model_name='pricingrule',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Highlight this pricing rule on the site'),
        ),
        migrations.AddField(
            model_name='pricingrule',
            name='order',
            field=models.IntegerField(default=0, help_text='Controls ordering of pricing cards'),
        ),
    ]
