# Generated by Django 6.0.2 on 2026-02-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_pricingrule_description_pricingrule_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingrule',
            name='display_label',
            field=models.CharField(default='Per Night', help_text="e.g., 'Nightly Rate', 'Weekly Rate', 'Monthly Rate'", max_length=50),
        ),
        migrations.AddField(
            model_name='pricingrule',
            name='display_price',
            field=models.DecimalField(decimal_places=2, default=200, help_text='Price to display on the card (e.g., 150 for per night, 1200 for weekly)', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pricingrule',
            name='display_price_unit',
            field=models.CharField(default='/night', help_text="e.g., '/night', '/7 nights', '/month'", max_length=50),
        ),
        migrations.AddField(
            model_name='pricingrule',
            name='features',
            field=models.TextField(blank=True, help_text='Features for this plan (one per line)'),
        ),
    ]
