# Generated by Django 6.0.2 on 2026-02-10 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_pricingrule_display_label_pricingrule_display_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('zelle', 'Zelle'), ('cashapp', 'Cash App'), ('debitcard', 'Debit Card')], max_length=20, null=True),
        ),
    ]
